services:

  database:
    image: "mysql:8.2.0-oraclelinux8"
    container_name: sense_core_mysql_db
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - "3309:3309"
    command: --port=3309
    volumes:
      - db-mysql-sense-core:/var/lib/mysql
    networks:
      - sense_services
      - auth_services
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "--port=3309", "--silent"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  sense-core-telemetry:
    image: cr.jaegertracing.io/jaegertracing/jaeger:2.9.0
    container_name: sense-core-telemetry
    environment:
      - COLLECTOR_OTLP_ENABLE=true
      - SPAN_STORAGE_TYPE=badger
      - BADGER_EPHEMERAL=false
      - BADGER_SPAN_STORE_TTL=168h0m0s  # 7 dias de retenção
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
      - "5778:5778"
      - "9411:9411"
    volumes:
      - jaeger-data:/badger
    networks:
      - sense_services
      - auth_services

  sense-core-server:
    image: diegoneves/sense-core-server:latest
    container_name: sense-core-api
    ports:
      - "8080:8080"
      - "5005:5005"
    depends_on:
      database:
        condition: service_healthy
    environment:
      # Configurações Quarkus para banco de dados
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:mysql://database:3309/${DB_NAME}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - QUARKUS_DATASOURCE_USERNAME=${DB_USERNAME}
      - QUARKUS_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - QUARKUS_HTTP_HOST=0.0.0.0
      - QUARKUS_HTTP_PORT=8080
      # Configurações da aplicação
      - API_VERSION=${API_VERSION:-latest}
      - QUARKUS_PROFILE=${QUARKUS_PROFILE:-prod}
      # Configurações de telemetria/observabilidade
      - QUARKUS_OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://sense-core-telemetry:4317
      - QUARKUS_OTEL_SERVICE_NAME=sense-core-server
      - QUARKUS_OTEL_TRACES_EXPORTER=otlp
      # Para debug remoto - CORRIGIDO
      - JAVA_OPTS=-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 --enable-native-access=ALL-UNNAMED
    networks:
      - sense_services
      - auth_services
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/q/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 45s

volumes:
  db-mysql-sense-core:
  jaeger-data:

networks:
  sense_services:
    driver: bridge
  auth_services:
    external: true
