name: 🐛 Bug Report
description: Reporte um bug para nos ajudar a melhorar
title: "[BUG] - "
labels: ["bug", "needs-triage"]
assignees:
  - username
body:
  - type: markdown
    attributes:
      value: |
        Obrigado por reportar este bug! Por favor, preencha as informações abaixo.

  - type: textarea
    id: what-happened
    attributes:
      label: O que aconteceu?
      description: Descreva o bug de forma clara e concisa
      placeholder: Conte-nos o que você viu!
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Passos para reproduzir
      description: Como podemos reproduzir este problema?
      value: |
        1. Vá para '...'
        2. Clique em '...'
        3. Role até '...'
        4. Veja o erro
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Comportamento esperado
      description: O que você esperava que acontecesse?
    validations:
      required: true

  - type: dropdown
    id: browsers
    attributes:
      label: Em quais navegadores isso acontece?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
